source 'https://github.com/CocoaPods/Specs.git'

target 'Analytics_Example', :exclusive => true do
  pod "Analytics", :path => "../"
  pod "Segment-GoogleAnalytics"
  pod "Segment-Amplitude"
end

target 'Analytics_Tests', :exclusive => true do
  pod "Analytics", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
